baseURL = "http://localhost:1313"
languageCode = "de-DE"
title = "Nacht der Wissenschaft Siegen"
disableKinds = ["taxonomy", "taxonomyTerm"]
relativeURLs = true
enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe= true