backend:
  name: github
  repo: TroogS/ndws-web
  branch: master # Branch to update (optional; defaults to master)

locale: 'de'
media_folder: "static/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
logo_url: ../img/head.svg
collections:

  - name: "single" # Used in routes, e.g., /admin/collections/blog
    label: "Single Page" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "program"
    label: "Programm"
    folder: "content/program"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "EventDate", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "talk"
    label: "Vortrag"
    folder: "content/talk"
    summary: "[{{relatedProgram}}] {{title}}"
    slug: ""
    path: "{{slug}}"
    create: true
    fields:
      - {
          label: "Gehört zum Program:",
          name: "relatedProgram",
          widget: "relation",
          collection: "program",
          valueField: "title",
          searchFields: ["title"],
        }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Vortragender", name: "name", widget: "string" }
      - { label: "Herkunft / Feld", name: "origin", widget: "string" }
      - { label: "Zeit", name: "time", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      