name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout Repo
      uses: actions/checkout@master
      
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.ACTIONS_DEPLOY_KEY }}
